// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rsk.Saml.OpenIddict.EntityFrameworkCore.DbContexts;

#nullable disable

namespace IdP.Migrations.OpenIddictSamlMessageDb
{
    [DbContext(typeof(OpenIddictSamlMessageDbContext))]
    partial class OpenIddictSamlMessageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Rsk.Saml.OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreSamlMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("longtext");

                    b.Property<string>("EntityId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreationTime");

                    b.HasIndex("Expiration");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("OpenIddctSamlMessages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
